// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountDetailsController from "./account_details_controller"
application.register("account-details", AccountDetailsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomepageSearchController from "./homepage_search_controller"
application.register("homepage-search", HomepageSearchController)

import HospitalSubscriptionController from "./hospital_subscription_controller"
application.register("hospital-subscription", HospitalSubscriptionController)

import MapController from "./map_controller"
application.register("map", MapController)

import MedicalRecordsController from "./medical_records_controller"
application.register("medical-records", MedicalRecordsController)

import PlanDetailsController from "./plan_details_controller"
application.register("plan-details", PlanDetailsController)
